kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 350M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/ars/Code/Personal/java/cars-reservation/apps/database/files
