/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nikitades.carres.shared;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsInstanceOf.instanceOf;

import org.junit.Test;

public class LibraryTest {

  @Test
  public void basicTest() {
    NewReservationNotification msg = new NewReservationNotification("a", "b", "c");
    assertThat(msg, instanceOf(NewReservationNotification.class));
  }
}
