spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://example.com
          audiences: app
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    enabled: true #auto migrate on startup
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /open/swagger-ui
    oauth:
      client-id: someclientid
      client-secret: someclientsecret
      use-basic-authentication-with-access-code-grant: true
