spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/carres
    username: carres
    password: carres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3001/auth/realms/carres
