datasource:
  url:
  username:
  password:
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://example.com
  datasource:
    url: jdbc:${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  r2dbc:
    url: r2dbc:${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: src/main/resources/changelog.sql

springdoc:
  swagger-ui:
    path: /open/swagger-ui
