datasource:
  url: postgresql://localhost:5433/carres
  username: carres
  password: carres
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3001/auth/realms/carres
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/db/migration/Vx_x_x__new_migration.sql
