spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carres
    username: carres
    password: carres
  # datasource:
  #   url: jdbc:h2:mem:carres;DATABASE_TO_LOWER=true;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  #   username: carres
    # password: #intentionally left empty
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://carres-keycloak:8080/realms/carres

  sql:
    init:
      mode: always
      data-locations: classpath:db/seeds/init.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      jakarta:
        persistence:
          schema-generation: #auto migration scripts generation rules
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/db/migration/Vx_x_x__dummy_migration.sql

  output:
    ansi:
      enabled: always

springdoc:
  swagger-ui:
    oauth:
      client-id: app
      client-secret: lpk2c9bzFFvLqnqeTGNCKWJq76UtENMf #for testing purpose only!

keycloak:
  admin:
    oauth:
      host: http://localhost:3001/auth
      realm: carres
      client-id: app
      client-secret: lpk2c9bzFFvLqnqeTGNCKWJq76UtENMf