apiVersion: apps/v1
kind: Deployment
metadata:
  name: carres-keycloak-deployment
  labels:
    app: carres-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carres-keycloak
  template:
    metadata:
      creationTimestamp: 2022-05-15T23:33:38Z
      labels:
        app: carres-keycloak
    spec:
      containers:
        - name: carres-keycloak
          image: nikitades/carres-keycloak:latest
          imagePullPolicy: Always
          args:
            [
              "start",
              "--optimized",
              "--http-enabled=true",
              "--hostname-strict-https=false",
              "--hostname-strict=false",
              "--proxy=passthrough",
            ]
          resources:
            limits:
              cpu: 300m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: carres-keycloak-config
                  key: database-url
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: carres-keycloak-secret
                  key: kc-db-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: carres-keycloak-secret
                  key: kc-db-password
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: carres-keycloak-secret
                  key: admin-username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: carres-keycloak-secret
                  key: admin-password
            - name: KC_HOSTNAME_URL
              valueFrom:
                configMapKeyRef:
                  name: carres-keycloak-config
                  key: hostname
            - name: KC_HOSTNAME_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: carres-keycloak-config
                  key: hostname
